### ISSUE TITLE
hola

### ISSUE THREAD

**Issue by joaquinsantana** [TheDeivit/Tolerante-a-Fallas#1]
buenas noches, no me permite añadir codigo :(

**Comment by Gamael17** [comment]
Buenas busco play chipeada

**Comment by joaquinsantana** [comment]
> Buenas busco play chipeada

https://articulo.mercadolibre.com.mx/MLM-555591232-play-station-2-chipeada-_JM#position=2&type=item&tracking_id=2b6fbb98-ad50-4e64-bbb1-7290611343e9

**Comment by TheDeivit** [comment]
Ya pueden subir código.
